### ISSUE TITLE
Replace Jax with PyTorch

### ISSUE THREAD

**Issue by qxcv** [HumanCompatibleAI/imitation#206]
[tabular_irl.py](https://github.com/HumanCompatibleAI/imitation/blob/master/src/imitation/algorithms/tabular_irl.py) is still using Jax. I should move it over to PyTorch so that we have one less dependency once we move to SB3.

**Comment by shwang** [comment]
Porting this is not a high priority for the beta release I think, especially if you are busy with other things.

We might want to consider moving this to the `imitation.contrib` folder, and making a Jax an optional dependency that we list on top of the `tabular_irl.py` file?

**Comment by AdamGleave** [comment]
Is there a reason to move it to contrib other than the Jax thing? I'm fine with this as a temporary thing, but it does seem nice to have tabular MCE IRL be a fully supported algorithm, since it's a natural baseline for environments where it is supported.

It does seem like quite a different API to the other algorithms right now though -- I suspect we can refactor it to be more like the others, but if not that would be an independent argument for contrib.

**Comment by shwang** [comment]
Resolved by #301.
