### ISSUE TITLE
How to generate expert data through manual control？

### ISSUE THREAD

**Issue by KevinHwangAi** [HumanCompatibleAI/imitation#214]
Hi everyone！
In my project, I hope to generate expert data through manual control。
What functions can I use to implement it?

**Comment by shwang** [comment]
Hi, not sure if you are still working on this issue since it's been a couple months now.

To use expert data with this repository you will need to track observations and actions over time and save them in the `imitation.data.types.Trajectory` format.

If by manual control, you mean keyboard input, then perhaps https://github.com/openai/gym/blob/master/examples/agents/keyboard_agent.py will come in handy.

We (the maintainers of the project) probably don't have the bandwidth to answer further questions on this topic right now, so I'm closing this issue.
