### ISSUE TITLE
PyTorch complains when we pass in Transitions because arrays are nonwritable

### ISSUE THREAD

**Issue by shwang** [HumanCompatibleAI/imitation#219]
After #208, we get warnings like

```
tests/test_dagger.py::test_trainer_makes_progress
  /pytorch/torch/csrc/utils/tensor_numpy.cpp:141: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program.
```

According to what I read online, this makes PyTorch copy the array before Tensor conversion (which TF1 had to do anyways, I'm pretty sure) and incurs a small speed cost compared to using mutable array. Luckily PyTorch is polite enough to not make this warning appear 100 times.

Might be nice to suppress this warning somehow.

**Comment by shwang** [comment]
Also I read that Pytorch can actually mutate the underlying numpy memory in some cases?

@qxcv I'm not very familiar with PyTorch -- I don't think this is the case, but do you know if there's any place in our code that would likely lead to numpy mutations?

As I understand it, one of the only ways you can mutate a numpy array after it is converted to a Tensor is by direct assignment to an element of that Tensor.

**Comment by qxcv** [comment]
> do you know if there's any place in our code that would likely lead to numpy mutations?

I don't, no. Mutations are generally not recommended in Torch networks because they complicate backprop code. Scott also asked me about this & I recommended to just suppress the warning in the BC forward prop/backprop code. I guess if we really wanted to, we could also figure out what code is declaring arrays unwritable & fix that. My bet is one some environment code caching an observation that it doesn't want to be written to, or maybe some multiprocessing code that is keeping arrays in shared memory somewhere.

**Comment by shwang** [comment]
I made the arrays in Transitions unwritable upon initialization.

**Comment by qxcv** [comment]
Ahhhh okay. Yeah, in that case I guess our best bet is just to silence the errors (or add a redundant copy if running on CPU :shrug:)
