### ISSUE TITLE
Trajectroy Recording and Generating

### ISSUE THREAD

**Issue by E666GT** [HumanCompatibleAI/imitation#260]
Dear SB3 and imitation support team,

may I know if there is an API to record the trajectory?

Thanks

**Comment by shwang** [comment]
You can generate rollouts as `imitation.type.Trajectory` or `Transitions` via functions defined in the `imitation.data.rollout` module.

You might also be interested in the [these wrappers](https://github.com/HumanCompatibleAI/imitation/blob/master/src/imitation/data/wrappers.py).

I'm closing this issue for now because I believe this answers all of your original question.
