### ISSUE TITLE
Question: Improving AIRL Performance on Cartpole

### ISSUE THREAD

**Issue by wisilva** [HumanCompatibleAI/imitation#310]
I have had trouble getting AIRL to perform well using trajectories from expert_demos.py (trained to completion with mean reward=498). When using train_adversarial.py (with no changes made to the hyperparameters), I saw good performance from GAIL, but the AIRL generator would always quickly drop to a reward of 9 (I believe this is indicative of the generator always taking the same action). Does AIRL generally perform well using the default hyperparameters for this script, and if not, is there a way to get the algorithm to perform better?  

More Info:
- The AIRL discriminator's accuracy increases continually throughout training until it reaches reaches nearly 100% (this accuracy never decreases).
- I saw similar results for both discriminator and generator performance when running AIRL through quickstart.py 
- I am not using the "fast" keyword when running train_adversarial.py (GAIL and AIRL are training to completion).

**Comment by AdamGleave** [comment]
Thanks for the report! First, sorry for having to discover stuff like this by trial and error -- we're aiming to put out a benchmark of imitation soon, plus tuned hyperparameters.

One common cause for major discrepancies between AIRL and GAIL is due to variable-horizon episodes inducing a bias. Effectively, if the learned reward / discriminator output is always positive, you'll try to prolong the episode (good for CartPole), if negative you'll try to end it early (bad for CartPole).

To remove this confounder, I'd suggest evaluating on a fixed-horizon version of the environment, e.g. we have one implemented in [seals](https://github.com/HumanCompatibleAI/seals/blob/master/src/seals/classic_control.py).

If GAIL and AIRL still perform very differently in that environment, we should definitely take a closer look, but I think that may clear it up.

**Comment by wisilva** [comment]
Thank you for the quick response! I tested adversarial on the seals_cartpole environment, but unfortunately neither algorithm performed well with the default parameters. In ~15 runs on GAIL and AIRL, the discriminator and generator trends varied, but environment reward did not reach above 200 for GAIL and 60 for AIRL. 

However, I was able to adapt a different domain that I am working with to a fixed-horizon environment, and I saw much better performance from of the AIRL implementation. Thank you for the advice!

**Comment by shwang** [comment]
Hi @wisilva, yesterday I got the following training curves for `seals/Cartpole` on

AIRL:
![image](https://user-images.githubusercontent.com/1750835/130157016-7d9b800e-5b2f-4b01-a295-0ff2c9ae2b96.png)

and GAIL:
![image](https://user-images.githubusercontent.com/1750835/130157117-d2f9785c-0cfe-416b-9c6d-0a6899fd5905.png)

**Comment by shwang** [comment]
I think the hyperparameters I'm using above are quite different from what's on `master` right now. I'll get back to this thread when I attempt to PR these changes today

**Comment by shwang** [comment]
@wisilva Please see #317 for GAIL/AIRL hyperparameters, and expert data downloads

**Comment by AdamGleave** [comment]
I assume Steven's responses have resolved your issue -- feel free to reopen if there's still a problem. We plan to post full benchmark results soon which may help as well.
