### ISSUE TITLE
GAIL/AIRL: fix bias discussed in discriminator-actor-critic paper

### ISSUE THREAD

**Issue by ejnnr** [HumanCompatibleAI/imitation#324]
This is essentially the same issue as #40 but I'm creating a new one rather than reopening because the code base has changed significantly and some of the discussion there is not very relevant anymore.

The [discriminator-actor-critic paper](https://arxiv.org/abs/1809.02925) describes a bias that GAIL (and apparently to a lesser extent also AIRL) suffer from in a variable-length horizon setting: in GAIL, the learned reward can never be negative, which biases the agent to aim for longer episodes. This is undesirable in some environments, where some goal should be achieved quickly. The DAC paper suggests fixing this bias by learning a reward for the final state rather than fixing it to zero.

#40 was closed under the assumption that #184 fixes the bias but as far as I can tell, that's not the case:
- GAIL doesn't use `RewardNet` at all, so it definitely still has this bias. What we need to do here is to add the fix inside the discriminator network, where the reward is computed
- For AIRL the issue is not the reward model, which can learn negative rewards anyway. If I understand the argument in the DAC paper correctly, this is more closely related to the discriminator loss and we should also add a fix inside the discriminator

I think the fix for GAIL is pretty straightforward, we need to learn a final reward and add it in `DiscrimNetGAIL.reward_train()` if `done` is `True`. Could be optional but should arguably be turned on by default? For AIRL I'm less sure what precisely we need to do. But presumably, the bias is also less critical there because the reward model can learn negative rewards.

**Comment by AdamGleave** [comment]
:+1: to raising this issue. The bias towards shorter/longer episodes bias is a common gremlin in reward learning evaluation, and has affected a number of `imitation` users.

I would be in favour of some attempt at fixing it. However, the best approach is murky to me.

In particular, on reflection I think I disagree with the characterization in the DAC paper of this being a bias. Really, variable-horizon is leaking information. This is undesirable for reward learning evaluation since the real-world does not come with reset conditions.

DAC's proposal of adding a learnable terminal reward solves the bias part, but I don't think it solves the information leakage.

So I'm actually wondering now if what we should do is just throw an error if we see variable-horizon episodes, and let people override that with a flag, e.g. `footgun_allow_variable_horizon = True`.

@qxcv @scottemmons do you have thoughts on this?

**Comment by scottemmons** [comment]
With the caveat that I haven't thought as deeply about this as you have, Adam, it seems right to me that a variable horizon will inherently leak information. I'd support taking the stance, "We don't officially support variable horizons, but if you really want to do it, you can use the override flag `footgun_allow_variable_horizon = True`."

**Comment by qxcv** [comment]
I agree w/ the flag idea as a way to make people think about whether this is actually what they want. Would like to emphasise that defining early termination conditions can make a lot of sense in realistic situations, though. e.g. if you're training your bipedal robot to make avocado toast, then it's probably fine to define early termination conditions like "robot falls over" or "toaster catches on fire", even if you don't know how to specify the finer points of the reward function.

**Comment by AdamGleave** [comment]
That's a fair point. Early termination is good for sample efficiency, and for that reason I'd be fine with variable horizon + DAC-like debiasing, so long as people are up-front about the termination condition in the eval.

I don't think we currently have environments we want to run `imitation` against which are (a) variable-horizon; (b) still have a highly non-trivial reward function after termination condition. So, implementing DAC-like debiasing doesn't seem like a priority, but I'd welcome a PR on it if/when it becomes actively useful.

**Comment by Stephanehk** [comment]
Quick question: I am implementing a custom environment where it is rather tricky (and extremely inefficient) to enforce a fixed horizon. Instead, when reward learning, I modify all collected trajectories such that they are all of the same lengths by manually adding transitions into an absorbing state if the given trajectory terminated early. Do you foresee any issues with leaking reward info here, when using a variable horizon while learning a policy but a fixed horizon when learning a reward model?

**Comment by AdamGleave** [comment]
> Quick question: I am implementing a custom environment where it is rather tricky (and extremely inefficient) to enforce a fixed horizon. Instead, when reward learning, I modify all collected trajectories such that they are all of the same lengths by manually adding transitions into an absorbing state if the given trajectory terminated early. Do you foresee any issues with leaking reward info here, when using a variable horizon while learning a policy but a fixed horizon when learning a reward model?

Padding with an absorbing state is pretty similar to what we do in [`AbsorbAfterDoneWrapper`](https://github.com/HumanCompatibleAI/seals/blob/master/src/seals/util.py#L182) except that's done at an environment level rather than modifying trajectories. Variable horizon for the policy will still leak some info, as the reward model can just learn a positive or negative reward for the absorbing state to incentivize longer or shorter episodes, in extreme cases reducing the problem to just learning a single bit. You could fix this by forcing the absorbing state to have reward zero, or by making the final reward be the return-to-go from staying in the absorbing state until the end of the horizon.

**Comment by AdamGleave** [comment]
I think it should though I'm not aware of a proof of this, so please do
verify.
