### ISSUE TITLE
dagger demos saved twice

### ISSUE THREAD

**Issue by hhroberthdaniel** [HumanCompatibleAI/imitation#402]
Hi,
I noticed a larger than expected number of demonstrations per round and I think i found the problem:

The demonstrations are saved both here:
https://github.com/HumanCompatibleAI/imitation/blob/9ca1e441ac4ee2c43f96a57b044cf625cab8b31a/src/imitation/algorithms/dagger.py#L635
and here:
https://github.com/HumanCompatibleAI/imitation/blob/9ca1e441ac4ee2c43f96a57b044cf625cab8b31a/src/imitation/algorithms/dagger.py#L259

Is this the expected behaviour?

**Comment by AdamGleave** [comment]
Thanks for opening the issue! This does look like a bug, as `DAggerTrainer.get_trajectory_collector` creates an `InteractiveTrajectoryCollector` which saves demos in https://github.com/HumanCompatibleAI/imitation/blob/9ca1e441ac4ee2c43f96a57b044cf625cab8b31a/src/imitation/algorithms/dagger.py#L259

`SimpleDaggerTrainer.train` uses that collector, but also saves its own demos, so it's duplicated. Duplication won't happen using `DaggerTrainer` directly I don't think.

Looks like this issue was introduced in https://github.com/HumanCompatibleAI/imitation/pull/309/files, I'll make a PR to remove https://github.com/HumanCompatibleAI/imitation/blob/9ca1e441ac4ee2c43f96a57b044cf625cab8b31a/src/imitation/algorithms/dagger.py#L635
