### ISSUE TITLE
The density baseline seems to be broken

### ISSUE THREAD

**Issue by ernestum** [HumanCompatibleAI/imitation#412]
Strongest indicator so far is, that the example notebook `density_baseline_demo.ipynb` can't be executed without errors.
#397 fixes this partially, but there seem to be more issues inside of `algorithms.density`.

**Comment by AdamGleave** [comment]
I've pushed a commit in #397 that makes the density baselines notebook demo work.

There were two errors I ran into:
  1. `reset()` called on `BufferingWrapper` before `pop_trajectories`. I fixed this by adding a relevant call to `pop_trajectories()`.
  2. `steps` not being provided when `is_stationary=False`. I worked around this by just setting `is_stationary=True`. This would require modifying `RewardVecEnvWrapper` to keep track of number of timesteps in episode so far to fix properly. Density algorithm is not a priority, so I feel OK with this functionality not being fully integrated.

Did you run into any other problems? If so, can you document them? Otherwise I think we can close this issue.

**Comment by ernestum** [comment]
Thanks for the fixes. So far the example file was my only indicator for the density estimator not working.
