### ISSUE TITLE
Randomness control for different `exploration_frac` in preference comparisons

### ISSUE THREAD

**Issue by yawen-d** [HumanCompatibleAI/imitation#420]
## Background
- Previously, [`exploration_frac`](https://github.com/HumanCompatibleAI/imitation/blob/3d7a76b8c587a25e380aeb09f65b764d7693aeea/src/imitation/algorithms/preference_comparisons.py#L212) was implemented to add exploratory trajectories for preference comparisons. Its aim was to add diversity to the dataset in order to escape from local minimum if any.
- In particular, `int(exploration_frac * steps)` transitions will be generated by [`\epsilon`-greedily](https://github.com/HumanCompatibleAI/imitation/blob/3d7a76b8c587a25e380aeb09f65b764d7693aeea/src/imitation/policies/exploration_wrapper.py#L62) apply the current policy after generating the normal transitions.

## Problems
1. Transition distribution shifts between normal vs. exploratory trajectories due to default `deterministic_policy` to be true.
2. Uncontrolled randomness among equivalent settings due to rounding, parallelisation and shuffling procedures.

### 1) Transition distribution shifts between normal vs. exploratory trajectories due to default `deterministic_policy` to be true for exploratory trajectories.
- For normal trajectories, policy actions are [generated stochastically](https://github.com/HumanCompatibleAI/imitation/blob/3d7a76b8c587a25e380aeb09f65b764d7693aeea/src/imitation/data/rollout.py#L305) (default to be non-deterministic policy).
- For exploratory trajectories, policy actions are [generated deterministically](https://github.com/HumanCompatibleAI/imitation/blob/3d7a76b8c587a25e380aeb09f65b764d7693aeea/src/imitation/algorithms/preference_comparisons.py#L167) from the [mode action](https://stable-baselines3.readthedocs.io/en/master/_modules/stable_baselines3/common/distributions.html#Distribution.get_actions) of the current policy distribution.
- Hence, the transition distribution shifts comes from (A) shifting between current policy and random policy, and (B) choosing actions deterministically with the highest probability. We indeed want (A) to increase exploration, but not (B) because (B) might strongly increase exploitation especially with a low `random_prob`.
- In extreme cases, for equivalent settings below, the training curves could be much different.
    a. `exploration_frac==0.0`
    b. `exploration_frac==0.2 & trajectory_generator_kwargs.random_prob=0.0`
<img width="500" alt="Screenshot 2022-03-15 at 16 29 09" src="https://user-images.githubusercontent.com/35738259/158488786-63473c29-131e-45f3-8539-7b10de5e53e8.png">

### 2) Uncontrolled randomness among equivalent settings due to rounding, parallelisation and shuffling procedures.
- Applying `rollout.generate_trajectories()` twice might increase the number of total trajectories sampled by 1 due to rounding issues.
- The algorithm buffer will collect all trajectories collected from all `SubProcessVecEnv`. Oversampling might happen if having a larger `common.num_vec`.
- Trajectories are shuffled twice when we apply `rollout.generate_trajectories()` twice.

## Solutions

1) Turn `deterministic_policy` to `False` for the [exploration wrapper](https://github.com/HumanCompatibleAI/imitation/blob/3d7a76b8c587a25e380aeb09f65b764d7693aeea/src/imitation/algorithms/preference_comparisons.py#L167).

2) It seems to take more changes to fix 2) by changing how we collect the trajectories. If the empirical results of fixing 1) show little difference between training curves, we might be able to ignore this.

**Comment by AdamGleave** [comment]
I agree 1) should be fixed, just making the deterministic policy consistent between both (likely defaulting to False) seems fine for now.

For 2) I think we should test empirically the difference across multiple seeds. If mean value is not statistically significantly different, I think it's OK for these to be different. If we wanted though we could probably fix the over-sampling by truncating (
but this is a bit of a waste of compute...) and shuffle once on the outside after concatenating the trajectories. There'll still be some differences though due to different environment initial states in the environment (it may have been reset more times in the exploration_frac>0 case), but this really should not change the distribution.

**Comment by kmdanielduan** [comment]
Here are some empirical results on 1):

It seems that adding deterministic trajectories indeed helps to learn faster, but I guess if we want to turn PPO to deterministic, we should do it when we initialise the algorithm, right? Otherwise, it could be hard to keep track of the version of algorithm we're using. This also suggests the problem (1) we identified indeed changes the trajectory distribution.
<img width="500" alt="Screenshot 2022-03-18 at 11 28 00" src="https://user-images.githubusercontent.com/35738259/159062074-493bed19-96ac-4f8f-a07a-a0d7165d4957.png">

By setting up deterministic policies for both normal and exploratory trajectories, here are some experiment results. It's hard to conclude different settings give similar results because of high variance across different seeds.

<img width="500" alt="Screenshot 2022-03-18 at 11 34 19" src="https://user-images.githubusercontent.com/35738259/159063174-aa452875-8f38-4f15-83e0-efcb5a3f022c.png">

**Comment by AdamGleave** [comment]
I don't think we want PPO to be deterministic. If I understand correctly, rollouts collected for purpose of RL training will always need to be stochastic (this is where the exploration comes from in policy gradients), so the trajectories we get from buffering wrapper will be stochastic. Probably best to keep it consistent stochastic everywhere.

If there's a big performance difference, we could consider not reusing the RL-sampled rollouts, and always sample deterministic trajectories ourselves. (This would also help avoid the mild difference in distribution between buffering wrapper, collected over multiple policy updates, and additional rollouts.) But while this might be more efficient in # of timesteps of reward training, it may not be in terms of wallclock time, as the buffering wrapper rollouts are effectively free.

To check I understand the first figure -- higher exploration_frac corresponds to higher # of deterministic samples? The SD of these is quite big, so I hesitate to conclude much, but it does look like exploration_frac (determinism, ironically) is positively correlated with return.
