### ISSUE TITLE
ValueError: Key 'mean\disc\disc_proportion_expert_true' truncated to 'mean\disc\disc_proportion_expert_...' that already exists. Consider increasing `max_length`.

### ISSUE THREAD

**Issue by limeng-1234** [HumanCompatibleAI/imitation#428]
When I try to run the "4_train_airl.ipynb" file, I got the error in the screenshot, how can I fix it?
![微信图片_20220407134654](https://user-images.githubusercontent.com/76480875/162129045-2c0f2d2c-d649-4e3a-a1e9-28f10ec7993a.png)

**Comment by AdamGleave** [comment]
Tagging @ernestum who made these demos. Have our keys got longer somehow since we wrote this?

As a workaround you can just call `configure` in https://github.com/HumanCompatibleAI/imitation/blob/fb743c8c3aefeac348e82d66e8c765e6984bd715/src/imitation/util/logger.py with `format_strs=['csv']`, disabling the `'stdout'` format string will prevent this codepath being hit.

**Comment by Zhengxuez** [comment]
Hi,

Have you tried Adam's method? I disabled the 'stdout', but still got the same error.

**Comment by AdamGleave** [comment]
I can't replicate this error, and these notebooks are being tested in the CI. I suspect this is an issue with using old PyPI version of imitation or outdated SB3. If anyone can replicate the error, please open a new issue including info on installed package versions.
