### ISSUE TITLE
Dealing with inconstent conventions for env observations: (h,w,c) vs (c,h,w)

### ISSUE THREAD

**Issue by dfilan** [HumanCompatibleAI/imitation#486]
Atari environments in gym return observations in (h,w,c) format. In stable baselines 3, policies are implemented in pytorch, which assumes (c,h,w) observations. As a result, stable baselines 3 has a few places where observations are transposed: in a wrapper applied to an environment when it's fed into a learning algorithm (see lines 163 and 224 of `stable_baselines3/common/base_class.py`), in some methods of policies (see lines 335 and 243 of `stable_baselines3/common/policies.py`), and possibly in other places. This means that when writing code, it is not always obvious whether this transposition has been applied to an environment.

For instance, the `__init__` method of `AgentTrainer` in `preference_comparisons.py` calls `self.algorithm.get_env()` to set the environment. Because `algorithm` must be a `BaseAlgorithm`, it wraps its input venv in a wrapper that transposes observations as necessary before returning that venv in the `get_env` method. 

This means that in the notebook `imitation/examples/5_train_preference_comparisons.ipynb`, if the environment is changed to be an Atari environment, `reward_net` is originally trained on inputs with format (c,h,w), but when placed in a `RewardVecEnvWrapper`, is called on inputs with format (h,w,c). This will likely cause poor performance, or in the case of a CNN reward net, a type error.

To deal with problems like this, the best solution is likely a wrapper around reward functions to detect when this transposition needs to be made and make it before it's fed into the naive reward function.

**Comment by AdamGleave** [comment]
Thanks for the write-up of the issue, Daniel! This is definitely a problem we should fix.

The fact that after calling `algorithm.set_env(venv)` we can have `algorithm.get_env() == VecTranspose(venv) != venv` is counterintuitive, and means things could easily break under our feet if SB3 changes its wrapping logic. For this reason I'd favor changing the logic in `preference_comparisons.py` (and any algorithms where we do something similar, maybe `AdversarialTrainer`) to take in the `venv` directly. That way our `BufferingWrapper` that records the transitions always sees the observations straight from the environment (plus any wrappers the user directly applied), and before any magic wrappers SB3 applies.

I think the change above is enough to fix the bug you highlight, as we'd be consistently using the input format `(h,w,c)`. *But* SB3 transposes to `(c,h,w)` for a reason -- it's what CNNs expect. We don't support have a CNN RewardNet right now -- but we probably should have one!

I can see a few ways to do the transposition for `imitation`:
  1. Make it the callees responsibility. Apply the transposition at the same time you do `AtariWrapper` and other preprocessing on the environment. This seems like the most flexible approach, and if we support it in our scripts `imitation` is still "batteries included".
  2. Have our CNN default to an `(h,w,c)` convention, and always do the transposition internally. This would play nice with Atari. But perhaps other environments have a different convention? Worth checking things like Malmo (MineRL) and other image-based environments.
  3. Optionally transpose internally to the CNN, based on magical detection of the observation space ala SB3. This is the most user friendly... until it misfires and causes subtle bugs.

I'm inclined to avoid 3, undecided between 1 and 2.

@qxcv do you have a take, I think you went for something like 1 in your code in https://github.com/HumanCompatibleAI/imitation/pull/221 ? 

@norabelrose do you have any thoughts on the best architecture here?

**Comment by AdamGleave** [comment]
Related issue: https://github.com/HumanCompatibleAI/imitation/issues/220

**Comment by norabelrose** [comment]
@AdamGleave Hmm I'm a little hesitant to add `venv` as an additional required argument of the `AgentTrainer` constructor, if that's what you were proposing. It seems like a redundant parameter since `algorithm` already contains the appropriate `venv`.
> The fact that after calling algorithm.set_env(venv) we can have algorithm.get_env() == VecTranspose(venv) != venv is counterintuitive, and means things could easily break under our feet if SB3 changes its wrapping logic.

I agree that this is odd behavior from SB3, but it seems like trying to "fix" their design mistake may only create more complexity. Could we simply make it the user's responsibility to manually apply `VecTransposeImage` before `RewardVecEnvWrapper` when needed? Or perhaps simply use `algorithm.get_env()` to get the auto-wrapped version of the environment.

@dfilan Does the notebook Just Work if you replace
```learned_reward_venv = RewardVecEnvWrapper(venv, reward_net.predict)```
with
```learned_reward_venv = RewardVecEnvWrapper(agent.get_env(), reward_net.predict)```?

**Comment by tomtseng** [comment]
I think changing the `learned_reward_venv = ...` line is already too late — we've already done something weird by training the reward net on inputs that don't match `reward_net.observation_space`, and we'd be avoiding the issue by continuing to apply the reward net on observations that don't match `reward_net.observation_space`. We could leave it to the user to initialize their reward net according to `algorithm.get_env()` instead of the original `venv`, but it'd be easy for the user to forget that they need to do this whenever they work with an image-based environment.

Passing `venv` as an additional requirement seems OK in the sense that since `algorithm` may change the env, it's reasonable for a function to want to have access to the env prior to `algorithm`'s transformations.

---

Re CNN transpositions:

Consistently assuming `(h,w,c)` from the env for CNNs is probably fine. I checked some `gym`-compatible environments, and I couldn't find any that output `(c,h,w)`:
- MineRL outputs `hwc` (verified by printing `observation_space`)
- Procgen outputs `hwc` (according to its README)
- `universe` outputs `hwc` (asserted in [unit test](https://github.com/openai/universe/blob/cc9ce6ec241821bfb0f3b85dd455bd36e4ee7a8c/tests/functional/test_envs.py#L71))
- VizDoom outputs `hwc` (asserted in [unit test](https://github.com/mwydmuch/ViZDoom/blob/6d70b5c7a1aa5ef64c011cc94f33758e324ab2fe/tests/test_gym_wrapper.py#L74))
- CARLA outputs `hwc` ([source code](https://github.com/cjy1992/gym-carla/blob/c01ae77d2729c618504595474b744a1641ec471f/gym_carla/envs/carla_env.py#L71))
- Duckietown outputs `hwc` (according to [README](https://github.com/duckietown/gym-duckietown#observations))
- Unity ML Agents outputs `hwc`? (Table 2 in [paper](https://arxiv.org/pdf/1809.02627.pdf))

In the (hopefully rare) case where an environment does output `(c,h,w)`, the user can apply a transposition wrapper to the env.

**Comment by AdamGleave** [comment]
Thanks for looking into this Tom! Great that's it's consistent. In this case just having our CNNs assume (h,w,c) and use raw observations as intermediate representation in all of our code seems like the right choice.

**Comment by dfilan** [comment]
Sorry, somehow missed this thread, but FWIW I ended up writing a PR with CNN reward functions and just wrapping the reward functions with a thing to transpose to `(c,h,w)`. https://github.com/HumanCompatibleAI/imitation/pull/519

**Comment by dfilan** [comment]
Given discussion here, probably what we want to do is always have CNNs check if their inputs are `(c,h,w)`, and if not transpose to put the channel first? Seems like this should be fine as long as we never see `(h,c,w)` inputs.

**Comment by tomtseng** [comment]
I don't love the idea that the transposition might incorrectly fire on some weird environment. Obviously the transposition detection will nearly always be correct in realistic scenarios, though, so I can't really say I'm opposed. Documenting it and testing it would be good.

**Comment by AdamGleave** [comment]
Given all the environments we've come across are (h,w,c), I think just assuming that and having a fixed transposition to (c,h,w) that PyTorch expects and cleanly documenting our convention is probably the cleanest.

I'm wary of auto-detecting as it can lead to very subtle bugs, better to fail loudly. I'd be fine adding optional transposition logic to the RewardNet if we ever come across an environment with a different convention to (h,w,c) though.

@dfilan even if we don't go with your transposition solution I think adding CNNs themselves will be very useful.

**Comment by dfilan** [comment]
Unfortunately, we can't necessarily assume that all environments we come across will be (h,w,c). In Atari, recommended preprocessing involves frame-stacking. If one does this using SB3's `VecFrameStack`, then the frame stack dimension (which in this case is basically the channel dimension) comes last, but if one instead does it using gym's `FrameStack`, the frame stack dimension comes first. In this case, it's possible that we should just mandate use of the SB3 method, but wanted to check if that changed your mind re: autotransposition.

**Comment by AdamGleave** [comment]
> Unfortunately, we can't necessarily assume that all environments we come across will be (h,w,c). In Atari, recommended preprocessing involves frame-stacking. If one does this using SB3's `VecFrameStack`, then the frame stack dimension (which in this case is basically the channel dimension) comes last, but if one instead does it using gym's `FrameStack`, the frame stack dimension comes first. In this case, it's possible that we should just mandate use of the SB3 method, but wanted to check if that changed your mind re: autotransposition.

Thanks for flagging this! Using `VecFrameStack` seems like the natural thing to do with `VecEnv`, so I feel OK about only that use case working out of the box, although it is a bit unfortunate.

I'm fine adding an option for transposition but would prefer to avoid auto-transposition logic.
