### ISSUE TITLE
Remove unused ` log_root` in `imitation.scripts.common`?

### ISSUE THREAD

**Issue by yawen-d** [HumanCompatibleAI/imitation#526]
## Problem

In `imitation.scripts.common`, the user is expected to specify a directory path to store the training statistics or artifacts by `common.log_root` or `common.log_dir`.

It seems that `log_root` is [not used anywhere](https://github.com/HumanCompatibleAI/imitation/search?q=log_root) in the source code except for `experiment/*.sh` and `tests/scripts/test_scripts.py`.

In [src/imitation/scripts/common/common.py](https://github.com/HumanCompatibleAI/imitation/blob/b8a4c369b3d6ee861ac84618dab1adcbaa537b26/src/imitation/scripts/common/common.py), `log_root` is also not used by any captured function.

https://github.com/HumanCompatibleAI/imitation/blob/41dafea0369a83894cde248fd649292be593638c/src/imitation/scripts/common/common.py#L22

This could potentially confuse the users and store unnecessary test data in the default paths during unit tests.

## Proposed Solution

- Remove `common.log_root` from `common`.
- Replace `log_root` with `log_dir` in
    - [experiments/dagger_benchmark.sh](https://github.com/HumanCompatibleAI/imitation/blob/47abd983dc4879b148d8b574226cab7ba0ea92ab/experiments/dagger_benchmark.sh), 
    - [experiments/imit_benchmark.sh](https://github.com/HumanCompatibleAI/imitation/blob/47abd983dc4879b148d8b574226cab7ba0ea92ab/experiments/imit_benchmark.sh), 
    - [experiments/transfer_learn_benchmark.sh](https://github.com/HumanCompatibleAI/imitation/blob/8efa8011545f00a86ee23f9e187f0db4a4367c8c/experiments/transfer_learn_benchmark.sh)
    - [tests/scripts/test_scripts.py](https://github.com/HumanCompatibleAI/imitation/blob/41dafea0369a83894cde248fd649292be593638c/tests/scripts/test_scripts.py)
    - [experiments/bc_benchmark.sh](https://github.com/HumanCompatibleAI/imitation/blob/47abd983dc4879b148d8b574226cab7ba0ea92ab/experiments/bc_benchmark.sh)
    - [experiments/rollouts_from_policies.sh](https://github.com/HumanCompatibleAI/imitation/blob/2ea8aaa025d22ec0e5c7cea337a3fff9b3117d9f/experiments/rollouts_from_policies.sh)
    - [src/imitation/scripts/common/common.py](https://github.com/HumanCompatibleAI/imitation/blob/b8a4c369b3d6ee861ac84618dab1adcbaa537b26/src/imitation/scripts/common/common.py)

**Comment by AdamGleave** [comment]
Thanks for spotting this. `log_root` used to serve a purpose of specifying the default root directory to create output in, if `log_dir` was not specified. Right now `log_dir` defaults to using `"output"` and ignores `log_root`. So, we could also just make a one-line change at https://github.com/HumanCompatibleAI/imitation/blob/db05631dc6f6ced4cf65aab86e6b29b18cd60c80/src/imitation/scripts/common/common.py#L43 to use `config["common"]["log_root"] or "output"` instead of `"output"` to re-enable it.

But if `log_root` has been broken since at least https://github.com/HumanCompatibleAI/imitation/blob/db05631dc6f6ced4cf65aab86e6b29b18cd60c80/src/imitation/scripts/common/common.py (Oct 2021) perhaps it is not so sorely missed and we should just delete it...

Thoughts?

**Comment by yawen-d** [comment]
`log_root` seems a reasonable design to me because I do replace "output" when running experiments. The one-liner solution looks good to me also. I don't really understand why it was deleted in the first place.

I opened a branch and pull request to track it.
