### ISSUE TITLE
Add mypy as a second type-checker

### ISSUE THREAD

**Issue by Rocamonde** [HumanCompatibleAI/imitation#532]
## Problem
 Pytype is a good inference-based type checker. However, this often leads to lots of false negatives when it cannot infer the type. Mypy is a good second pair of eyes that looks only at type annotations, but will likely introduce lots of false positives.

## Solution
Add mypy, but not enforcing this in CI initially if it produces a lot of false positives.

## Possible alternative solutions
Alternative type checkers can be suggested. Mypy seems to be extremely well supported and popular, so it seems to be the default choice.

**Comment by AdamGleave** [comment]
I'm in favor of adding another type checker. I do think if it's producing false positives we need to address that either by adding type annotations or suppressing it -- checks are largely useless unless they're enforced. One option might be to add a check that a PR doesn't introduce *new* warnings.

I agree mypy is a natural choice though worth looking at alternatives -- it's been a while since I did that.

I just ran it against our source code and it says:
```Found 155 errors in 32 files (checked 66 source files)```
which is not so bad. About half of them are that it can't analyze `gym` and other third parties since it doesn't have library stubs.

**Comment by Rocamonde** [comment]
> I just ran it against our source code and it says:
> `Found 155 errors in 32 files (checked 66 source files)`
> which is not so bad. About half of them are that it can't analyze `gym` and other third parties since it doesn't have library stubs.

Yes, working on that right now. Will keep you updated

**Comment by Rocamonde** [comment]
I have fixed the types of most of the codebase. I have added comments in those places where an obvious fix was not available, potentially pointing out a bug in the types or the code. There are a few files that have particularly many errors, those in the algorithms module.
