### ISSUE TITLE
Nobody can figure out how to get rollouts of policies trained on image environments

### ISSUE THREAD

**Issue by dfilan** [HumanCompatibleAI/imitation#599]
## Problem
In issues #547 and #596, people try training an SB3 policy (let's call it `expert`) on some image environment (let's call it `my_img_env`) and then generating rollouts by calling `rollout.rollout(expert, my_img_env, sample_until_whatever)`.

The problem is that this doesn't work. `my_img_env` is basically always (h,w,c)-formatted, and the training of `expert` always involved internally transposing to (c,h,w) before feeding it into the policy. The code that people should write is `rollout.rollout(expert, expert.get_env(), sample_until_whatever)`.

How are people supposed to know they should do this? It's not a very natural thing to do - I don't think anybody learns about this feature of SB3 before running into it when it causes a bug, it's kind of weird that `expert` has a `get_env` method in the first place, and the documentation for `rollout.rollout` doesn't warn them that anything might go wrong.

## Possible solutions
- indicate that this can go wrong in the documentation of `rollout.rollout`
- indicate that this can go wrong in some tutorial
- change `rollout.rollout` so that it tries to transpose stuff in case of an observation space mismatch

**Comment by AdamGleave** [comment]
Thanks for raising the issue, Daniel.

I think our first port of call should be to add an example to our [CNN preference comparison tutorial](https://github.com/HumanCompatibleAI/imitation/blob/master/docs/tutorials/5a_train_preference_comparisons_with_cnn.ipynb) and generally document the weirdness of their being different conventions between `imitation`/`torch` and `stable-baselines3`. We should also add more informative error messages -- so if someone tries to do this, they get a message linking to the docs, rather than just some weird shape error.

Long-term I'd like a solution that either eliminates this complexity (e.g. make SB3 consistent), or (since that might break a lot of existing SB3 users) some adaptor layer that hides most of this complexity from users. Perhaps we will get inspiration for that when writing the docs.

Assigning this to you @dan-pandori to work on next week. But it's a thorny issue, we should discuss in person.

**Comment by dfilan** [comment]
Closed as solved by #618.

**Comment by Disastorm** [comment]
I think I'm getting this or something similar to this when using BufferingWrapper.pop_transitions()  , is this also another expected location that will be different dimensions?
