### ISSUE TITLE
questions about class Trajectory

### ISSUE THREAD

**Issue by nianba** [HumanCompatibleAI/imitation#699]
I have no idea that why the shape of obs of "class imitation.data.types.Trajectory(obs, acts, infos, terminal)" should be "trajectory_len + 1".
Thanks a lot!

**Comment by LeonHenne** [comment]
Facing the same issue. 
Following error occurs after sampling the expert trajectories.
`ValueError: expected one more observations than actions: 2578 != 2578 + 1`

**Comment by dfilan** [comment]
The basic deal happening here is that a Trajectory is a sequence like this:
(first observation, first action, second observation, second action, ..., `trajectory_len`th observation, `trajectory_len`th action, (`trajectory_len` + 1)th observation).
This is because most environments we're dealing with have a final observation after the final action, after which you don't get the chance to submit another action.

**Comment by LeonHenne** [comment]
Understand. Do you perhaps know a general way to make sure that a custom environment doesn't produce another action to the (`trajectory_len`+1)th observation. Im sorry quite a beginner question 😅

**Comment by nianba** [comment]
Thanks! Now I know how to generate my own trajectories!
